version: "3"
services:
    my_elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
        container_name: my_elasticsearch
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elastic
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data

    my_kibana:
        image: docker.elastic.co/kibana/kibana:8.15.3
        container_name: my_kibana
        environment:
            - SERVER_NAME=my_kibana
            - ELASTICSEARCH_HOSTS=http://my_elasticsearch:9200
        ports:
            - 5601:5601
        networks:
            - elastic

networks:
    elastic:

volumes:
    elasticsearch_data:
